// =============================================================
// HORRIBLE CARDS — the deck
// Edit / add to these to your taste. Black cards are prompts.
// White cards are responses. `pick: 2` black cards have two
// blanks and players submit two white cards in order.
// =============================================================

const BLACK_CARDS = [
  { text: "What's a girl's best friend?", pick: 1 },
  { text: "What ended my last relationship?", pick: 1 },
  { text: "Daddy, why is mommy crying?", pick: 1 },
  { text: "What gets better with age?", pick: 1 },
  { text: "What's my secret power?", pick: 1 },
  { text: "Why am I sticky?", pick: 1 },
  { text: "What's that smell?", pick: 1 },
  { text: "I never truly understood ___ until I encountered ___.", pick: 2 },
  { text: "What did I bring back from Mexico?", pick: 1 },
  { text: "TSA guidelines now prohibit ___ on airplanes.", pick: 1 },
  { text: "Coming this Christmas: ___ 2: Electric Boogaloo.", pick: 1 },
  { text: "Why am I crying in the Olive Garden bathroom?", pick: 1 },
  { text: "What did I sacrifice for these abs?", pick: 1 },
  { text: "What's the next forbidden TikTok trend?", pick: 1 },
  { text: "What did the cult promise me?", pick: 1 },
  { text: "Tonight's special at Applebee's: ___ smothered in ___.", pick: 2 },
  { text: "What's the most unsexy thing to whisper during sex?", pick: 1 },
  { text: "What's in Putin's nightstand?", pick: 1 },
  { text: "I'm sorry professor, I couldn't do the homework because of ___.", pick: 1 },
  { text: "What's banned at the church potluck?", pick: 1 },
  { text: "What did my therapist diagnose me with?", pick: 1 },
  { text: "Why was I escorted off the cruise ship?", pick: 1 },
  { text: "The Pope's new encyclical declares ___ a mortal sin.", pick: 1 },
  { text: "What's hiding in my roommate's closet?", pick: 1 },
  { text: "Yelp review: 'One star. ___.'", pick: 1 },
  { text: "I'll have a venti latte with ___ and a side of ___.", pick: 2 },
  { text: "What's the worst thing to overhear at a baby shower?", pick: 1 },
  { text: "Florida Man arrested for ___.", pick: 1 },
  { text: "What's the secret to my marriage?", pick: 1 },
  { text: "Mom found my collection of ___.", pick: 1 },
  { text: "What does Jeff Bezos do with all that money?", pick: 1 },
  { text: "What's God's biggest oopsie?", pick: 1 },
  { text: "My new memoir is titled '___: A Life.'", pick: 1 },
  { text: "What's the new Olympic event?", pick: 1 },
  { text: "What's worse than finding a hair in your soup?", pick: 1 },
  { text: "Why did I get fired from Chuck E. Cheese?", pick: 1 },
  { text: "What's the new MTV reality show?", pick: 1 },
  { text: "What's the worst thing to find in your kid's backpack?", pick: 1 },
  { text: "What's the safe word at Burning Man?", pick: 1 },
  { text: "I'm gonna need a bigger ___.", pick: 1 },
  { text: "What's the next conspiracy theory?", pick: 1 },
  { text: "My ex's new partner is really into ___.", pick: 1 },
  { text: "What did I do to get banned from the petting zoo?", pick: 1 },
  { text: "Why is the Pope sweating?", pick: 1 },
  { text: "What's the secret menu item at Taco Bell?", pick: 1 },
  { text: "What's grandpa's secret recipe?", pick: 1 },
  { text: "Tonight on Dateline: 'A Story of ___.'", pick: 1 },
  { text: "What's my villain origin story?", pick: 1 },
  { text: "What did I find in the Airbnb?", pick: 1 },
  { text: "What's the new requirement for U.S. citizenship?", pick: 1 },
  { text: "I get turned on by ___ and ___.", pick: 2 },
  { text: "Why am I no longer welcome at IHOP?", pick: 1 },
  { text: "What's the worst thing to find under your bed at age 35?", pick: 1 },
  { text: "Coming to Disney+ this summer: ___, but make it horny.", pick: 1 },
  { text: "What's the new HOA rule?", pick: 1 },
  { text: "I asked Santa for ___ but I got ___ instead.", pick: 2 },
  { text: "What's haunting this Airbnb?", pick: 1 },
  { text: "The new Subway sandwich features ___.", pick: 1 },
  { text: "What did I scream at my Uber driver?", pick: 1 },
  { text: "Why did my Tinder date ghost me?", pick: 1 },
  { text: "What's the new flavor of Mountain Dew?", pick: 1 },
  { text: "What's the safe word at the White House?", pick: 1 },
  { text: "TripAdvisor warning: 'Beware of ___ at this resort.'", pick: 1 },
  { text: "What's the latest Goop product?", pick: 1 },
  { text: "My funeral playlist opens with ___.", pick: 1 },
  { text: "What ruined Thanksgiving this year?", pick: 1 },
  { text: "What did my parents walk in on me doing?", pick: 1 },
  { text: "What's the next big wellness trend?", pick: 1 },
  { text: "Why is my Roomba covered in ___?", pick: 1 },
  { text: "What's the worst icebreaker at a swingers party?", pick: 1 },
  { text: "Lifetime presents: '___: The ___ Story.'", pick: 2 },
  { text: "What did I name my emotional support animal?", pick: 1 },
  { text: "What's that smell in the church basement?", pick: 1 },
  { text: "What's the secret ingredient in McDonald's special sauce?", pick: 1 },
  { text: "What did I write in my LinkedIn bio?", pick: 1 },
  { text: "Why was I asked to leave the funeral?", pick: 1 },
  { text: "What does Mark Zuckerberg do to feel human?", pick: 1 },
  { text: "Coming up next on Fox News: '___: Is your child at risk?'", pick: 1 },
  { text: "What's the new Pope's first executive order?", pick: 1 },
  { text: "What's banned in 23 countries?", pick: 1 },
  { text: "What did I find in the dumpster behind Hooters?", pick: 1 },
  { text: "What's the worst gift to give your in-laws?", pick: 1 },
  { text: "What does my dog dream about?", pick: 1 },
  { text: "What does the inside of Elon Musk's brain look like?", pick: 1 },
  { text: "I lost my virginity to ___ in a ___.", pick: 2 },
  { text: "Surgeon general's warning: ___ may cause ___.", pick: 2 },
  { text: "What's the secret to looking 30 years younger?", pick: 1 },
  { text: "What did the fortune cookie REALLY say?", pick: 1 },
  { text: "Why did Karen call the manager?", pick: 1 },
  { text: "What does heaven smell like?", pick: 1 },
  { text: "What does hell smell like?", pick: 1 },
  { text: "What's the worst part about being a clown?", pick: 1 },
  { text: "I will not be silenced about ___.", pick: 1 },
  { text: "What's the next Squid Game challenge?", pick: 1 },
  { text: "What's the new Netflix true crime documentary about?", pick: 1 },
  { text: "Why is my therapist quitting the profession?", pick: 1 },
  { text: "What did my Catholic guilt manifest as?", pick: 1 },
  { text: "What's the next big crypto scam?", pick: 1 },
  { text: "What's the worst part of growing up?", pick: 1 },
  { text: "Why is my Uber rating 1.3?", pick: 1 },
  { text: "What's the new exercise craze sweeping the suburbs?", pick: 1 },
  { text: "I got 99 problems but ___ ain't one.", pick: 1 },
  { text: "What's my safe word?", pick: 1 },
  { text: "Therapist: 'And what caused the divorce?' Me: '___.'", pick: 1 },
  { text: "What's the worst thing to find in your Uber?", pick: 1 },
  { text: "Breaking news: Local man arrested for ___ at Costco.", pick: 1 },
  { text: "Tonight on HBO: a gritty reboot of ___ starring ___.", pick: 2 },
  { text: "What's the title of my upcoming TED Talk?", pick: 1 },
  { text: "I'm not saying I'm proud of ___, but here we are.", pick: 1 },
  { text: "What's hiding under my bed?", pick: 1 },
  { text: "Coming to Netflix this fall: '___: The Musical.'", pick: 1 },
  { text: "What's the most unsexy thing to find on a first date?", pick: 1 },
  { text: "Last words: '___.'", pick: 1 },
  { text: "What's the worst Halloween costume?", pick: 1 },
  { text: "My OnlyFans is called '___.'", pick: 1 },
  { text: "What did I do during my mental breakdown?", pick: 1 },
  { text: "Why am I in the principal's office?", pick: 1 },
  { text: "What's the next billion-dollar startup?", pick: 1 },
  { text: "Officer, I can explain. That isn't ___, it's ___.", pick: 2 },
  { text: "My yoga instructor caught me doing ___ in the studio.", pick: 1 },
  { text: "What's the rejected Disney princess movie about?", pick: 1 },
  { text: "What's the new requirement to get verified on Twitter?", pick: 1 },
  { text: "Why am I trending on Twitter?", pick: 1 },
  { text: "What's the worst thing to do on a Zoom call?", pick: 1 },
  { text: "What's the secret behind the Mona Lisa's smile?", pick: 1 },
  { text: "What turned grandma into a tankie?", pick: 1 },
  { text: "Why am I banned from Disneyland for life?", pick: 1 },
];

const WHITE_CARDS = [
  "My crippling student debt",
  "An aggressively horny ghost",
  "Three raccoons in a trench coat",
  "Daddy issues with their own zip code",
  "A surprisingly aggressive Roomba",
  "The sweet release of death",
  "Putin's shirtless equestrian phase",
  "Getting railed by a Build-A-Bear",
  "My ex's new partner who's somehow worse than me",
  "A urinal cake with feelings",
  "Aggressively making eye contact during the deed",
  "Whatever Elon Musk named his kid this week",
  "Pegging the patriarchy",
  "A wet fart in church",
  "Sending unsolicited nudes to my dentist",
  "The clown that lives in my walls",
  "Toxic masculinity, but make it fashion",
  "An NDA I really shouldn't have signed",
  "A condom full of birthday cake",
  "Mommy's special juice",
  "Two pumps and a Hail Mary",
  "Generational trauma",
  "A fursuit that has seen things",
  "Crippling alcoholism dressed up as wine mom culture",
  "My deeply problematic search history",
  "Slappin' the bishop in a Wendy's bathroom",
  "Ranch dressing as a personality",
  "An emotional support inflatable pool noodle",
  "Whatever the hell furries are doing",
  "My DMs after 2 AM",
  "Dying alone surrounded by cats who are also dying",
  "A drunk Santa at the office Christmas party",
  "Public masturbation, but artistically",
  "The Vatican's secret porn collection",
  "An Amazon return I emotionally cannot make",
  "Choking on my own ambition",
  "The DM I sent to my high school English teacher",
  "A communion wafer dipped in lube",
  "Climbing into my therapist's lap",
  "Crying in a Cheesecake Factory bathroom",
  "Whatever the hell is going on in Florida",
  "Edging until I cry",
  "A clown with crippling depression",
  "Getting cucked by a houseplant",
  "Erotic asphyxiation gone hilariously wrong",
  "The horny demon I summoned by accident",
  "Aggressive twerking at a funeral",
  "A handjob from a Disney princess",
  "The lingering smell of WD-40 and regret",
  "Three loads in one go",
  "Whatever Mark Zuckerberg actually is",
  "The wet, slapping sound of justice",
  "A weighted blanket made of human hair",
  "A teacher who is just NOT okay",
  "The forbidden Capri Sun",
  "Pissing into the void",
  "An OnlyFans page nobody asked for",
  "Twerking through the trauma",
  "My fursona, who is also my therapist",
  "Getting railed in a Cracker Barrel parking lot",
  "A wet, gentle queef",
  "The CIA torturing me with smooth jazz",
  "A really clammy handshake",
  "Mommy's wine o'clock",
  "Being painfully, painfully bisexual",
  "The clap (and not the applause kind)",
  "Doing meth with my landlord",
  "A really enthusiastic priest",
  "The horny, horny moon",
  "Whatever's growing in the back of the fridge",
  "Aggressively flirting with a corpse",
  "A Tinder match who turned out to be my cousin",
  "The smell of off-brand Axe body spray",
  "A truly upsetting amount of body hair",
  "Sucking off a robot for warmth",
  "An Amazon Alexa that has seen too much",
  "Existential dread, but make it horny",
  "The wet, sad sigh of my Honda Civic",
  "Crying while making sweet, sweet love",
  "A wet sock full of disappointment",
  "Doing a line of crushed Adderall off a textbook",
  "The mailman who has SEEN things",
  "A boner that won't quit (medical emergency)",
  "Mommy and daddy fighting again",
  "A nun with surprising upper body strength",
  "The forbidden raw chicken",
  "Whatever's in the trunk",
  "Getting dommed by a Roomba",
  "A Christian rock band that's secretly into BDSM",
  "Three Adderall and a Red Bull",
  "An ex who keeps coming back like herpes",
  "Tongue-kissing my landlord for rent",
  "A Bath & Body Works bomb going off",
  "Polyamory, but everyone hates each other",
  "A raccoon in a wedding dress",
  "Gentle, sad humping",
  "The forbidden glue stick",
  "A medically inadvisable amount of Plan B",
  "Crying during a Pixar movie",
  "Aggressively kegeling at a job interview",
  "The wet sound of capitalism collapsing",
  "Bezos in the bald cowboy hat era",
  "A church lock-in that got weird",
  "Manifesting via primal scream",
  "Hot girl IBS",
  "A goth child who's never been hugged",
  "Doing my taxes in a Spirit Halloween wig",
  "An emotional Costco run",
  "The horny pilgrim spirit",
  "A wet, betrayed sigh",
  "Crying while eating a Crunchwrap Supreme",
  "The forbidden waterslide",
  "Bukkake at the bar mitzvah",
  "Three feral preschoolers in a Costco",
  "A nun on a Segway",
  "Sliding into the wrong DMs (twice)",
  "Bottoming for the algorithm",
  "An entire family-size Doritos bag, alone, in the dark",
  "My toxic situationship",
  "A clown's first kiss",
  "The wet ghost of Christmas past",
  "Sending 'wyd' to my dead grandmother",
  "Aggressive pegging in a Hyundai Elantra",
  "A horny Roomba named Beatrice",
  "Tongue-fucking my own reflection",
  "An MLM that's also a sex cult",
  "A truly catastrophic queef",
  "Getting horny at the DMV",
  "Crying into a Whataburger",
  "A pumpkin spice latte made of tears",
  "The smell of WD-40 and divorce",
  "Going down on a mall Santa",
  "A child's birthday party gone awry",
  "Sad masturbation in a Holiday Inn Express",
  "A fart so wet it's a war crime",
  "Being haunted by my Wii Fit Mii",
  "An IUD with a vendetta",
  "Cumming while crying",
  "A really upsetting amount of tongue",
  "Getting cancelled by my own mother",
  "A Walmart manager who has given up",
  "The smell of a Spirit Halloween at midnight",
  "A genuinely unhinged Facebook post",
  "Twink death",
  "A truly ferocious yeast infection",
  "Doing acid at a Chuck E. Cheese",
  "An MLM girlboss with bad teeth",
  "Mommy's third margarita",
  "A Christmas card from my ex's mom",
  "A wet, regretful 'I love you'",
  "Three different STDs (none of which are mine)",
  "Performing oral on a houseplant",
  "Whatever's leaking from my ceiling",
  "A really, really wet sneeze",
  "Crying into my Stanley cup",
  "The wet thwack of consequence",
  "Bottoming through the depression",
  "An aggressively horny pilgrim",
  "Sucking face with the grim reaper",
  "A Build-A-Bear stuffed with regret",
  "Getting evicted mid-orgasm",
  "Mommy's gentle parenting voice",
  "A nervous breakdown at Trader Joe's",
  "A dad who's just discovered TikTok",
  "An entire jar of Nutella, with my hands",
  "The horny revenge of nature",
  "Whatever Gwyneth Paltrow is selling",
  "A child catching me cry-masturbating",
  "Power-bottoming for Christ",
  "Three Diet Cokes and a Klonopin",
  "An Amish girl on her Rumspringa",
  "Getting railed against the Yankee Candle display",
  "A clown crying in a Subaru",
  "My terrible, terrible taste in men",
  "A genuinely upsetting Buffalo Wild Wings",
  "Mommy's bunco night",
  "A truly inappropriate amount of saliva",
  "Spit-roasting a wax figure of Lincoln",
  "An emotionally unavailable Pomeranian",
  "Sucking off a vending machine for snacks",
  "Crying at my own bachelorette party",
  "Aggressive, sustained eye contact",
  "Two girls, one truly upsetting taxidermy raccoon",
  "Whatever the deal is with Mike Pence's wife",
  "A condom found in the church parking lot",
  "Mommy's pickleball league",
  "Going down on a clown (he's into it)",
  "A meth lab in a Build-A-Bear factory",
  "Aggressive, full-tongue communion",
  "Three teenage girls in a Sephora",
  "A wet, sad, sustained moan",
  "The horny aftermath of a yoga retreat",
  "Choking out a fellow Whole Foods shopper",
  "A divorced uncle at the cookout",
  "An OnlyFans subscription I cannot explain",
  "Bottoming for the empire",
  "A really aggressive ASMR video",
  "Mommy's quinoa bowl",
  "A wet pilgrim hat",
  "An exorcism that turned sexual",
  "Crying at a Cinnabon",
  "A truly upsetting amount of glitter",
  "Getting cancelled at age 9",
  "The wet thunk of failure",
  "A boner during the eulogy",
  "Sliding into Jesus's DMs",
  "An incompetent dom",
  "A nun on Adderall",
  "The smell of pickleball and adultery",
  "Whatever Joe Rogan's been smoking",
  "Three Adderall, a Klonopin, and a manifesting journal",
  "A clown shocked at his own depravity",
  "Getting horny watching Antiques Roadshow",
  "Mommy's energy work",
  "A really upsetting Sephora",
  "Aggressive missionary in a Honda Odyssey",
  "Crying during my LinkedIn endorsements",
  "The wet sound of millennial despair",
  "Doing a sex act on a Roomba (the Roomba is named Linda)",
  "A boner at a baby's baptism",
  "Whatever's wrong with Florida",
  "Sucking off a Big Mouth Billy Bass",
  "Aggressive eye contact at the urinal",
  "An entire family of raccoons in formalwear",
  "Mommy's pickle vodka",
  "A wet sad gay in a Wendy's",
  "Sliding into a confessional",
  "Three Twinks in a Trenchcoat (it's a band)",
  "Cumming so hard I see God",
  "A truly disturbing Spirit Halloween costume",
  "Getting railed to completion at Bed Bath & Beyond",
  "A clown realizing he's the punchline",
  "Mommy's juice cleanse",
  "Stage-five clinger energy",
  "An obsessive crush on my GP",
  "A wet, broken laugh",
  "Crying into my matcha",
  "Going down on a sentient KitchenAid mixer",
  "Aggressive twerking at a Bar Mitzvah",
  "A child's drawing that revealed too much",
  "Whatever fresh hell my mother-in-law brought",
  "Bottoming for the algorithm — again",
  "A genuinely concerning Etsy purchase",
  "Sucking dick for the discount",
  "Three TikTok teens in a Tahoe",
  "A wet, sad, divorced dad on a jet ski",
  "Mommy's reiki session",
  "A horny demon trapped in a Furby",
  "An emotional support golden retriever with bad vibes",
  "Getting wet at a Sam's Club",
  "A truly upsetting amount of leg hair",
  "Three sad gays in a Subaru",
  "Aggressively flirting with my divorce attorney",
  "A communion that turned French",
  "Bottoming through the apocalypse",
  "Mommy's affirmation journal",
  "An Amish boy in his first Uber",
  "Whatever's in the trunk of my Subaru",
  "A grandmother who has just discovered weed",
  "The horny ghost of a Founding Father",
  "Crying through orgasm",
  "A clown trying to cum",
  "The forbidden Big Gulp",
  "Mommy's beachbody coaching",
  "A wet, slappy birthday",
  "An ankle bracelet that's not just for fashion",
  "Three Build-A-Bears in a poly throuple",
  "A truly horrific yard sale",
  "Bottoming for breakfast",
  "Sliding into the Pope's DMs",
  "A clown's wet, sad first time",
  "Whatever drugs Costco is putting in the rotisserie chickens",
  "Two pumps, a squirt, and a sorry",
  "An entire Trader Joe's worth of frozen mandarin chicken",
  "A Catholic girl on her first day of college",
  "Mommy's pickleball injury",
  "Getting railed at a TJ Maxx",
  "A Costco sample tray that ruined my marriage",
  "Three goth kids in a Whole Foods",
  "Crying while assembling IKEA",
  "Sucking off a TSA agent for an upgrade",
  "A clown's nervous breakdown",
  "A genuinely upsetting fart",
  "Mommy's third bottle of pinot",
  "Whatever Steve Buscemi is up to",
  "A horny pumpkin",
  "Bottoming for tenure",
  "Aggressive, sustained twerking",
  "A wet sad lesbian in a U-Haul",
  "An entire Cheesecake Factory menu, alone, weeping",
  "Sliding into Mother Teresa's DMs",
  "Three feral cats in a Costco",
  "Mommy's emergency hysterectomy",
  "A vampire who's just on Lexapro now",
  "An exorcist on his lunch break",
  "Crying in front of the DoorDash guy",
  "Getting horny at Hobby Lobby",
  "A truly cataclysmic queef in yoga class",
  "Whatever the actual fuck Gwyneth Paltrow is doing now",
  "Going through customs with that",
  "Mommy's micro-cheating",
  "A wet, slappy goodbye",
  "Three Mormons in a Tinder photo",
  "An aggressive Build-A-Bear bukkake",
  "Whatever Dr. Oz is selling",
  "A genuinely terrifying Karen",
  "Sliding into a manger",
  "Mommy's hot girl walks",
  "Getting cucked by a Bath & Body Works candle",
  "Three Ambien and a road trip",
  "A wet sad goth in a Hot Topic",
  "Aggressive missionary at a missionary's funeral",
  "An Amish Tinder",
  "Crying while ovulating",
  "Bottoming for a sandwich",
  "A clown's emotional support clown",
  "Whatever the fuck a 'Karen' is doing now",
  "Mommy's pickleball orgy",
  "A nun's bachelorette party",
  "Three furries in a Honda Fit",
  "Bottoming on the Sabbath",
  "A sustained, unwelcome erection",
  "Aggressive twerking on a yacht",
  "A clown bottoming for a mime",
  "Crying through my colonoscopy",
  "Going down on Mr. Peanut",
  "An OnlyFans for feet only",
  "Mommy's microdose",
  "A confessional that turned French",
  "An emotional Bath & Body Works",
  "Bottoming for a Cinnabon",
  "Three sad raccoons in a Costco",
  "Whatever happened to my hairline",
  "A wet birthday wish",
  "An exorcist's bachelor party",
  "Mommy's energy healer named Brad",
  "Aggressively horny at Trader Joe's",
  "Three pilgrims in a porta-potty",
  "A clown's secret OnlyFans",
  "Whatever Florida is doing today",
  "An unholy union at the Olive Garden",
  "Mommy's Pilates instructor named Chad",
  "Getting horny at Pottery Barn",
  "A wet, sad bukkake at a Bar Mitzvah",
  "Three sad clowns in a Honda Civic",
  "Bottoming for a HOA seat",
  "A truly upsetting wedding registry",
  "Aggressive eye contact in a Wendy's drive-thru",
];

// Shuffle helper — used to mix the decks
function shuffle(array) {
  const a = array.slice();
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
